name: "Bug Report"
description: "Submit a bug report"
body:
- type: textarea
  id: expected_behavior
  attributes:
    label: "Expected Behavior" 
    placeholder: "Tell us what should happen"
  validations:
    required: true
- type: textarea
  id: current_behavior
  attributes:
    label: "Current Behavior"
    placeholder: "Tell us what happens instead of the expected behavior"
  validations:
    required: true
- type: textarea
  id: possible_solution
  attributes:
    label: "Possible Solution"
  validations:
    required: false
- type: textarea
  id: steps_to_reproduce
  attributes:
    label: "Steps to reproduce"
  validations:
    required: true
